//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBATeams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        public int CoachId { get; set; }
        public string Naam { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Teams Team { get; set; }
    }
}
