//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBATeams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NBATeamsEntities2 : DbContext
    {
        public NBATeamsEntities2()
            : base("name=NBATeamsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coaches> Coaches { get; set; }
        public virtual DbSet<Spelers> Spelers { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
